/*
	Copyright (c) 2016 Pedro Magalhães

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "ext/standard/info.h"
#include "Zend/zend.h"
#include "Zend/zend_types.h"
#include "Zend/zend_extensions.h"
#include "Zend/zend_vm_opcodes.h"
#include "php_ulopcodes.h"

/* If you declare any globals in php_ulopcodes.h uncomment this:
ZEND_DECLARE_MODULE_GLOBALS(ulopcodes)
*/

/* {{{ PHP_INI
 */
/* Remove comments and fill if you need to have entries in php.ini
PHP_INI_BEGIN()
    STD_PHP_INI_ENTRY("ulopcodes.global_value",      "42", PHP_INI_ALL, OnUpdateLong, global_value, zend_ulopcodes_globals, ulopcodes_globals)
    STD_PHP_INI_ENTRY("ulopcodes.global_string", "foobar", PHP_INI_ALL, OnUpdateString, global_string, zend_ulopcodes_globals, ulopcodes_globals)
PHP_INI_END()
*/
/* }}} */

/* {{{ proto string confirm_ulopcodes_compiled(string arg)
   Dummy function to be found in the oparray */
PHP_FUNCTION(ulopcodes_emit)
{

}
/* }}} */

/* {{{ php_ulopcodes_init_globals
 */
/* Uncomment this function if you have INI entries
static void php_ulopcodes_init_globals(zend_ulopcodes_globals *ulopcodes_globals)
{
	ulopcodes_globals->global_value = 0;
	ulopcodes_globals->global_string = NULL;
}
*/
/* }}} */

/* {{{ PHP_MINIT_FUNCTION
 */
PHP_MINIT_FUNCTION(ulopcodes)
{
	/*
		Copy from zend_vm_opcodes.h

		Find: ^#define (ZEND_[^ ]*).*$
		Replace: REGISTER_LONG_CONSTANT("$1", $1, CONST_CS|CONST_PERSISTENT);
	*/
	REGISTER_LONG_CONSTANT("ZEND_NOP", ZEND_NOP, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ADD", ZEND_ADD, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SUB", ZEND_SUB, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_MUL", ZEND_MUL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DIV", ZEND_DIV, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_MOD", ZEND_MOD, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SL", ZEND_SL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SR", ZEND_SR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CONCAT", ZEND_CONCAT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BW_OR", ZEND_BW_OR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BW_AND", ZEND_BW_AND, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BW_XOR", ZEND_BW_XOR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BW_NOT", ZEND_BW_NOT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BOOL_NOT", ZEND_BOOL_NOT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BOOL_XOR", ZEND_BOOL_XOR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_IS_IDENTICAL", ZEND_IS_IDENTICAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_IS_NOT_IDENTICAL", ZEND_IS_NOT_IDENTICAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_IS_EQUAL", ZEND_IS_EQUAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_IS_NOT_EQUAL", ZEND_IS_NOT_EQUAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_IS_SMALLER", ZEND_IS_SMALLER, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_IS_SMALLER_OR_EQUAL", ZEND_IS_SMALLER_OR_EQUAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CAST", ZEND_CAST, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_QM_ASSIGN", ZEND_QM_ASSIGN, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_ADD", ZEND_ASSIGN_ADD, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_SUB", ZEND_ASSIGN_SUB, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_MUL", ZEND_ASSIGN_MUL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_DIV", ZEND_ASSIGN_DIV, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_MOD", ZEND_ASSIGN_MOD, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_SL", ZEND_ASSIGN_SL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_SR", ZEND_ASSIGN_SR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_CONCAT", ZEND_ASSIGN_CONCAT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_BW_OR", ZEND_ASSIGN_BW_OR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_BW_AND", ZEND_ASSIGN_BW_AND, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_BW_XOR", ZEND_ASSIGN_BW_XOR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_PRE_INC", ZEND_PRE_INC, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_PRE_DEC", ZEND_PRE_DEC, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_POST_INC", ZEND_POST_INC, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_POST_DEC", ZEND_POST_DEC, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN", ZEND_ASSIGN, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_REF", ZEND_ASSIGN_REF, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ECHO", ZEND_ECHO, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_GENERATOR_CREATE", ZEND_GENERATOR_CREATE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMP", ZEND_JMP, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMPZ", ZEND_JMPZ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMPNZ", ZEND_JMPNZ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMPZNZ", ZEND_JMPZNZ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMPZ_EX", ZEND_JMPZ_EX, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMPNZ_EX", ZEND_JMPNZ_EX, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CASE", ZEND_CASE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CHECK_VAR", ZEND_CHECK_VAR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_VAR_NO_REF_EX", ZEND_SEND_VAR_NO_REF_EX, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_MAKE_REF", ZEND_MAKE_REF, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BOOL", ZEND_BOOL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FAST_CONCAT", ZEND_FAST_CONCAT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ROPE_INIT", ZEND_ROPE_INIT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ROPE_ADD", ZEND_ROPE_ADD, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ROPE_END", ZEND_ROPE_END, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BEGIN_SILENCE", ZEND_BEGIN_SILENCE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_END_SILENCE", ZEND_END_SILENCE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_FCALL_BY_NAME", ZEND_INIT_FCALL_BY_NAME, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DO_FCALL", ZEND_DO_FCALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_FCALL", ZEND_INIT_FCALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_RETURN", ZEND_RETURN, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_RECV", ZEND_RECV, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_RECV_INIT", ZEND_RECV_INIT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_VAL", ZEND_SEND_VAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_VAR_EX", ZEND_SEND_VAR_EX, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_REF", ZEND_SEND_REF, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_NEW", ZEND_NEW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_NS_FCALL_BY_NAME", ZEND_INIT_NS_FCALL_BY_NAME, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FREE", ZEND_FREE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_ARRAY", ZEND_INIT_ARRAY, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ADD_ARRAY_ELEMENT", ZEND_ADD_ARRAY_ELEMENT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INCLUDE_OR_EVAL", ZEND_INCLUDE_OR_EVAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_UNSET_VAR", ZEND_UNSET_VAR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_UNSET_DIM", ZEND_UNSET_DIM, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_UNSET_OBJ", ZEND_UNSET_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FE_RESET_R", ZEND_FE_RESET_R, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FE_FETCH_R", ZEND_FE_FETCH_R, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_EXIT", ZEND_EXIT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_R", ZEND_FETCH_R, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_DIM_R", ZEND_FETCH_DIM_R, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_OBJ_R", ZEND_FETCH_OBJ_R, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_W", ZEND_FETCH_W, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_DIM_W", ZEND_FETCH_DIM_W, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_OBJ_W", ZEND_FETCH_OBJ_W, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_RW", ZEND_FETCH_RW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_DIM_RW", ZEND_FETCH_DIM_RW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_OBJ_RW", ZEND_FETCH_OBJ_RW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_IS", ZEND_FETCH_IS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_DIM_IS", ZEND_FETCH_DIM_IS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_OBJ_IS", ZEND_FETCH_OBJ_IS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_FUNC_ARG", ZEND_FETCH_FUNC_ARG, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_DIM_FUNC_ARG", ZEND_FETCH_DIM_FUNC_ARG, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_OBJ_FUNC_ARG", ZEND_FETCH_OBJ_FUNC_ARG, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_UNSET", ZEND_FETCH_UNSET, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_DIM_UNSET", ZEND_FETCH_DIM_UNSET, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_OBJ_UNSET", ZEND_FETCH_OBJ_UNSET, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_LIST", ZEND_FETCH_LIST, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_CONSTANT", ZEND_FETCH_CONSTANT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_EXT_STMT", ZEND_EXT_STMT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_EXT_FCALL_BEGIN", ZEND_EXT_FCALL_BEGIN, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_EXT_FCALL_END", ZEND_EXT_FCALL_END, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_EXT_NOP", ZEND_EXT_NOP, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_TICKS", ZEND_TICKS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_VAR_NO_REF", ZEND_SEND_VAR_NO_REF, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CATCH", ZEND_CATCH, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_THROW", ZEND_THROW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_CLASS", ZEND_FETCH_CLASS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CLONE", ZEND_CLONE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_RETURN_BY_REF", ZEND_RETURN_BY_REF, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_METHOD_CALL", ZEND_INIT_METHOD_CALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_STATIC_METHOD_CALL", ZEND_INIT_STATIC_METHOD_CALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ISSET_ISEMPTY_VAR", ZEND_ISSET_ISEMPTY_VAR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ISSET_ISEMPTY_DIM_OBJ", ZEND_ISSET_ISEMPTY_DIM_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_VAL_EX", ZEND_SEND_VAL_EX, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_VAR", ZEND_SEND_VAR, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_USER_CALL", ZEND_INIT_USER_CALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_ARRAY", ZEND_SEND_ARRAY, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_USER", ZEND_SEND_USER, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_STRLEN", ZEND_STRLEN, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DEFINED", ZEND_DEFINED, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_TYPE_CHECK", ZEND_TYPE_CHECK, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_VERIFY_RETURN_TYPE", ZEND_VERIFY_RETURN_TYPE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FE_RESET_RW", ZEND_FE_RESET_RW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FE_FETCH_RW", ZEND_FE_FETCH_RW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FE_FREE", ZEND_FE_FREE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INIT_DYNAMIC_CALL", ZEND_INIT_DYNAMIC_CALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DO_ICALL", ZEND_DO_ICALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DO_UCALL", ZEND_DO_UCALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DO_FCALL_BY_NAME", ZEND_DO_FCALL_BY_NAME, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_PRE_INC_OBJ", ZEND_PRE_INC_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_PRE_DEC_OBJ", ZEND_PRE_DEC_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_POST_INC_OBJ", ZEND_POST_INC_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_POST_DEC_OBJ", ZEND_POST_DEC_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_OBJ", ZEND_ASSIGN_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_OP_DATA", ZEND_OP_DATA, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_INSTANCEOF", ZEND_INSTANCEOF, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_CLASS", ZEND_DECLARE_CLASS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_INHERITED_CLASS", ZEND_DECLARE_INHERITED_CLASS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_FUNCTION", ZEND_DECLARE_FUNCTION, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_YIELD_FROM", ZEND_YIELD_FROM, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_CONST", ZEND_DECLARE_CONST, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ADD_INTERFACE", ZEND_ADD_INTERFACE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_INHERITED_CLASS_DELAYED", ZEND_DECLARE_INHERITED_CLASS_DELAYED, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_VERIFY_ABSTRACT_CLASS", ZEND_VERIFY_ABSTRACT_CLASS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_DIM", ZEND_ASSIGN_DIM, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ISSET_ISEMPTY_PROP_OBJ", ZEND_ISSET_ISEMPTY_PROP_OBJ, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_HANDLE_EXCEPTION", ZEND_HANDLE_EXCEPTION, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_USER_OPCODE", ZEND_USER_OPCODE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSERT_CHECK", ZEND_ASSERT_CHECK, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_JMP_SET", ZEND_JMP_SET, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_LAMBDA_FUNCTION", ZEND_DECLARE_LAMBDA_FUNCTION, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ADD_TRAIT", ZEND_ADD_TRAIT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BIND_TRAITS", ZEND_BIND_TRAITS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEPARATE", ZEND_SEPARATE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_CLASS_NAME", ZEND_FETCH_CLASS_NAME, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_CALL_TRAMPOLINE", ZEND_CALL_TRAMPOLINE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DISCARD_EXCEPTION", ZEND_DISCARD_EXCEPTION, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_YIELD", ZEND_YIELD, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_GENERATOR_RETURN", ZEND_GENERATOR_RETURN, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FAST_CALL", ZEND_FAST_CALL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FAST_RET", ZEND_FAST_RET, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_RECV_VARIADIC", ZEND_RECV_VARIADIC, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SEND_UNPACK", ZEND_SEND_UNPACK, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_POW", ZEND_POW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ASSIGN_POW", ZEND_ASSIGN_POW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BIND_GLOBAL", ZEND_BIND_GLOBAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_COALESCE", ZEND_COALESCE, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_SPACESHIP", ZEND_SPACESHIP, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_ANON_CLASS", ZEND_DECLARE_ANON_CLASS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_DECLARE_ANON_INHERITED_CLASS", ZEND_DECLARE_ANON_INHERITED_CLASS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_STATIC_PROP_R", ZEND_FETCH_STATIC_PROP_R, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_STATIC_PROP_W", ZEND_FETCH_STATIC_PROP_W, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_STATIC_PROP_RW", ZEND_FETCH_STATIC_PROP_RW, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_STATIC_PROP_IS", ZEND_FETCH_STATIC_PROP_IS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_STATIC_PROP_FUNC_ARG", ZEND_FETCH_STATIC_PROP_FUNC_ARG, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_STATIC_PROP_UNSET", ZEND_FETCH_STATIC_PROP_UNSET, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_UNSET_STATIC_PROP", ZEND_UNSET_STATIC_PROP, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ISSET_ISEMPTY_STATIC_PROP", ZEND_ISSET_ISEMPTY_STATIC_PROP, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_CLASS_CONSTANT", ZEND_FETCH_CLASS_CONSTANT, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BIND_LEXICAL", ZEND_BIND_LEXICAL, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_BIND_STATIC", ZEND_BIND_STATIC, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_FETCH_THIS", ZEND_FETCH_THIS, CONST_CS|CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("ZEND_ISSET_ISEMPTY_THIS", ZEND_ISSET_ISEMPTY_THIS, CONST_CS|CONST_PERSISTENT);

	REGISTER_LONG_CONSTANT("ZEND_VM_LAST_OPCODE", ZEND_VM_LAST_OPCODE, CONST_CS|CONST_PERSISTENT);

	return SUCCESS;
}
/* }}} */

/* {{{ PHP_MINFO_FUNCTION
 */
PHP_MINFO_FUNCTION(ulopcodes)
{
	php_info_print_table_start();
	php_info_print_table_header(2, "ulopcodes support", "enabled");
	php_info_print_table_end();

	/* Remove comments if you have entries in php.ini
	DISPLAY_INI_ENTRIES();
	*/
}
/* }}} */

/* {{{ ulopcodes_functions[]
 *
 * Every user visible function must have an entry in ulopcodes_functions[].
 */
const zend_function_entry ulopcodes_functions[] = {
	PHP_FE(ulopcodes_emit,	NULL)
	PHP_FE_END	/* Must be the last line in ulopcodes_functions[] */
};
/* }}} */

/* {{{ ulopcodes_module_entry
 */
zend_module_entry ulopcodes_module_entry = {
	STANDARD_MODULE_HEADER,
	PHP_ULOPCODES_NAME,
	ulopcodes_functions,
	PHP_MINIT(ulopcodes),
	NULL,
	NULL,
	NULL,
	PHP_MINFO(ulopcodes),
	PHP_ULOPCODES_VERSION,
	STANDARD_MODULE_PROPERTIES
};
/* }}} */

ZEND_DLEXPORT int ulop_startup(zend_extension *extension)
{
	return zend_startup_module(&ulopcodes_module_entry);
}

ZEND_DLEXPORT void ulop_oparray_h(zend_op_array *op_array)
{
	unsigned int i;

	// if(op_array->function_name) {
	// 	php_printf("Function: %s\n", op_array->function_name->val);
	// } else {
	// 	php_printf("Function: (no name)\n");
	// }

	for (i = 0; i < op_array->last; i++) {
		/*
			If we find a call to the dummy function on the opcodes
		*/
		if (op_array->opcodes[i].opcode == ZEND_INIT_FCALL &&
			op_array->opcodes[i].op2_type == IS_CONST &&
			op_array->literals[op_array->opcodes[i].op2.constant].u1.v.type == IS_STRING &&
			op_array->literals[op_array->opcodes[i].op2.constant].value.str->len == strlen("ulopcodes_emit") &&
			strcmp(op_array->literals[op_array->opcodes[i].op2.constant].value.str->val, "ulopcodes_emit") == 0 //&& false
		) {
			zend_uchar opcode = 0;
			znode_op op1;
			znode_op op2;
			zend_uchar op1_type = IS_UNUSED;
			zend_uchar op2_type = IS_UNUSED;

			unsigned int j = i + 1;
			unsigned int found = 0;

			op_array->opcodes[i].opcode = ZEND_NOP;

			/*
				Get the operands from the SEND_VAL calls that follow
			*/
			while ((op_array->opcodes[j].opcode != ZEND_DO_ICALL) && (j < op_array->last - 1)) {
				if (op_array->opcodes[j].opcode == ZEND_SEND_VAL || op_array->opcodes[j].opcode == ZEND_SEND_VAR) {
					if (found == 0) {
						/*
							Get the user's opcode
						*/
						if (op_array->literals[op_array->opcodes[j].op1.constant].value.lval > ZEND_VM_LAST_OPCODE) {
							php_error(E_ERROR, "Unknown opcode passed to ulopcodes_emit.");
						} else {
							opcode = op_array->literals[op_array->opcodes[j].op1.constant].value.lval;
						}
						op_array->opcodes[j].opcode = ZEND_NOP;
					} else if (found == 1) {
						/*
							Get the first op
						*/
						op1_type = op_array->opcodes[j].op1_type;
						op1 = op_array->opcodes[j].op1;
						op_array->opcodes[j].opcode = ZEND_NOP;
					} else if (found == 2) {
						/*
							Get the second op
						*/
						op2_type = op_array->opcodes[j].op1_type;
						op2 = op_array->opcodes[j].op1;
						op_array->opcodes[j].opcode = ZEND_NOP;
					}
					found++;
				}
				j++;
			}
			if (found > 0) {
				op_array->opcodes[j].opcode = opcode;
			}
			if (found > 1) {
				op_array->opcodes[j].op1 = op1;
				op_array->opcodes[j].op1_type = op1_type;
			}
			if (found > 2) {
				op_array->opcodes[j].op2 = op2;
				op_array->opcodes[j].op2_type = op2_type;
			}
		}

		// if (op_array->opcodes[i].opcode < ZEND_VM_LAST_OPCODE) {
		// 	if (op_array->opcodes[i].opcode == ZEND_INIT_FCALL && op_array->opcodes[i].op2_type == IS_CONST) {
		// 		php_printf("Fcall Target: %s\n", op_array->literals[op_array->opcodes[i].op2.constant].value.str->val);
		// 	}
		// 	php_printf("Opcode: %s (%d - %d) (%d - %d)\n",
		// 		zend_get_opcode_name(op_array->opcodes[i].opcode), 
		// 		op_array->opcodes[i].op1_type, 
		// 		op_array->opcodes[i].op1.num, 
		// 		op_array->opcodes[i].op2_type, 
		// 		op_array->opcodes[i].op2.num
		// 	);
		// } else {
		// 	php_printf("Opcode: UNKNOWN\n");
		// }
	}

	// php_printf("End function\n");
}

#ifndef ZEND_EXT_API
#define ZEND_EXT_API    ZEND_DLEXPORT
#endif
ZEND_EXTENSION();

ZEND_DLEXPORT zend_extension zend_extension_entry = {
	PHP_ULOPCODES_NAME,
	PHP_ULOPCODES_VERSION,
	PHP_ULOPCODES_AUTHOR,
	PHP_ULOPCODES_URL,
	PHP_ULOPCODES_COPYRIGHT,
	ulop_startup,		/* startup_func_t */
	NULL,				/* shutdown_func_t */
	NULL,           	/* activate_func_t */
	NULL,           	/* deactivate_func_t */
	NULL,           	/* message_handler_func_t */
	ulop_oparray_h,     /* op_array_handler_func_t */
	NULL, 				/* statement_handler_func_t */
	NULL,				/* fcall_begin_handler_func_t */
	NULL,				/* fcall_end_handler_func_t */
	NULL,   			/* op_array_ctor_func_t */
	NULL,           	/* op_array_dtor_func_t */
	STANDARD_ZEND_EXTENSION_PROPERTIES
};

#ifdef COMPILE_DL_ULOPCODES
#ifdef ZTS
ZEND_TSRMLS_CACHE_DEFINE()
#endif
ZEND_GET_MODULE(ulopcodes)
#endif
